---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - python-lxml

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

  # Build docker with new configurations
  - cd tests
  - docker build --tag="cscfi/shibboleth-idp-test:latest" .
  - docker run --name="test" cscfi/shibboleth-idp-test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
